# Generated by Django 4.2.6 on 2023-11-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseordermodel',
            name='items',
            field=models.JSONField(default=dict),
        ),
    ]
