# Generated by Django 4.2.6 on 2023-11-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0003_purchaseordermodel_acknowledged'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseordermodel',
            name='Completed',
            field=models.BooleanField(auto_created=True, default=False),
        ),
        migrations.AddField(
            model_name='purchaseordermodel',
            name='created',
            field=models.BooleanField(auto_created=True, default=False),
        ),
    ]
